# Generated by Django 4.1.7 on 2023-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Sell'), (2, 'Purchase')], default=1, max_length=1),
        ),
    ]
